Add min_id_length in settings
pyepye/django-amplitude pull request #2
Opened 2020-12-14 20:47 UTC by yuekui

According to [documentation](https://developers.amplitude.com/docs/http-api-v2#properties-2), we could set `min_id_length` in settings to support short user identifiers.

2020-12-15 14:06 UTC, pyepye commented
Hey @yuekui 

Thanks for the pull request. I'm a little busy today but should get a chance to look at it tomorrow.

2020-12-15 16:21 UTC, yuekui commented
> Hey @yuekui
> 
> Thanks for the pull request. I'm a little busy today but should get a chance to look at it tomorrow.

No problem, thanks for review 👍

2020-12-23 00:27 UTC, pyepye requested changes
Hi @yuekui

I've requested some changes:
* Removing the `AMPLITUDE_MIN_ID_LENGTH` from `test/settings.py` so it's not set by default in the tests
* Making sure `MIN_ID_LENGTH` is a `int` in the settings (and a test for it)
* Setting `min_id_length` to `None` by default, instead setting it's value in the Amplitude `__init__()`

I've tried to leave clear feedback as to why with some help. if you are a more experience Python programmer and understand please ignore. It was not meant to be condescending but as help as I appreciate the work you have already put in.

Also with that in mind, if anything isn't clear I've also created a branch with the changes as an example - https://github.com/pyepye/django-amplitude/tree/min_id_length_changes 

Thanks again
Matt

2020-12-23 00:27 UTC, pyepye commented on amplitude/settings.py
> +MIN_ID_LENGTH = getattr(settings, 'AMPLITUDE_MIN_ID_LENGTH', None)
Could we please make sure that `MIN_ID_LENGTH` in an integer?

```suggestion
MIN_ID_LENGTH = getattr(settings, 'AMPLITUDE_MIN_ID_LENGTH', None)
if MIN_ID_LENGTH and not isinstance(MIN_ID_LENGTH, int):
    raise ImproperlyConfigured('"AMPLITUDE_MIN_ID_LENGTH" must be an integer')
```

Then for a test in `test/settings.py`
```
def test_min_id_length(settings):
    settings.AMPLITUDE_MIN_ID_LENGTH = 'test'

    with pytest.raises(ImproperlyConfigured) as error:
        from amplitude import settings as appsettings
        reload(appsettings)
    error.match('"AMPLITUDE_MIN_ID_LENGTH" must be an integer')
```

2020-12-23 00:27 UTC, pyepye commented on tests/settings.py
> +AMPLITUDE_MIN_ID_LENGTH = 2
Could we leave this unset by default as it's an optional argument in both Amplitude and in the settings file.
This will also remove the need to add it to all of the tests now and in the future

2020-12-23 00:27 UTC, pyepye commented on amplitude/amplitude.py
> +        min_id_length: int = app_settings.MIN_ID_LENGTH,
Setting the default variable in the args isn't best practise. It's better to set it to `None` and then deal with the possible none value in the init / function body. 

With the current implementation `app_settings.MIN_ID_LENGTH` will be run once when the module is loaded where as moving the assignment into the `__init__()` will run the line each time a new `Amplitude()` is instantiated. This is important as it means the `Amplitude()` class cannot be used outside of Django with this current implementation.

It also means that if the Django settings were to be reloaded without restarting Django fully the min_id_length would not be updated. While this is generally not much of an issue it's still better to make it possible.

For example the following test fails:
```python
def test_send_events_with_min_id_length(mocker, settings):
    settings.AMPLITUDE_MIN_ID_LENGTH = 100
    from amplitude import settings as appsettings
    reload(appsettings)

    amplitude = Amplitude()
    mock = mocker.Mock()
    mock.json.return_value = {
        'code': 200,
        'server_upload_time': 1111111111111,
        'payload_size_bytes': 111,
        'events_ingested': 1
    }
    request = mocker.patch(
        'amplitude.amplitude.httpx.request', return_value=mock
    )
    events = [{'fake': {'fake': 'fake'}}]
    response = amplitude.send_events(events)
    assert isinstance(response, dict)
    kwargs = {
        'url': 'https://api.amplitude.com/2/httpapi',
        'method': 'POST',
        'json': {
            'events': events,
            'api_key': appsettings.API_KEY,
            'options': {
                'min_id_length': settings.AMPLITUDE_MIN_ID_LENGTH
            }
        }
    }
    request.assert_called_once_with(**kwargs)
```

But it will pass with
```python
class Amplitude():

    def __init__(
        self,
        api_key: str = None,
        include_user_data: bool = None,
        include_group_data: bool = None,
        min_id_length: int = None,
    ):
        if not api_key:
            api_key = app_settings.API_KEY
        if include_user_data is None:
            include_user_data = app_settings.INCLUDE_USER_DATA
        if include_group_data is None:
            include_group_data = app_settings.INCLUDE_GROUP_DATA
        if not min_id_length:
            min_id_length = app_settings.MIN_ID_LENGTH

        self.url = 'https://api.amplitude.com/2/httpapi'
        self.api_key = api_key
        self.include_user_data = include_user_data
        self.include_group_data = include_group_data
        self.min_id_length = min_id_length
```

2020-12-23 00:27 UTC, pyepye commented on tests/test_amplitude.py
> +        min_id_length=settings.MIN_ID_LENGTH + 1,
As `MIN_ID_LENGTH` should be removed from the `test/settings.py` please set this to it's own variable instead of using `settings.MIN_ID_LENGTH`

2020-12-23 00:27 UTC, pyepye commented on tests/test_amplitude.py
> +    amplitude = Amplitude(min_id_length=100)
As we test `min_id_length` works in the `test_init_pass_args()` test and `AMPLITUDE_MIN_ID_LENGTH` is going to be removed from the `test/settings.py`, could we run this by setting the `AMPLITUDE_MIN_ID_LENGTH` in the test?

```python
settings.AMPLITUDE_MIN_ID_LENGTH = 100
from amplitude import settings as appsettings
reload(appsettings)
amplitude = Amplitude()
```

2020-12-23 02:34 UTC, yuekui commented
> Hi @yuekui
> 
> I've requested some changes:
> 
>     * Removing the `AMPLITUDE_MIN_ID_LENGTH` from `test/settings.py` so it's not set by default in the tests
> 
>     * Making sure `MIN_ID_LENGTH` is a `int` in the settings (and a test for it)
> 
>     * Setting `min_id_length` to `None` by default, instead setting it's value in the Amplitude `__init__()`
> 
> 
> I've tried to leave clear feedback as to why with some help. if you are a more experience Python programmer and understand please ignore. It was not meant to be condescending but as help as I appreciate the work you have already put in.
> 
> Also with that in mind, if anything isn't clear I've also created a branch with the changes as an example - https://github.com/pyepye/django-amplitude/tree/min_id_length_changes
> 
> Finally sorry this code review is later than promised.
> 
> Thanks again
> Matt

Hi Matt, thanks so much for your review and detailed description, that's really helpful! I will fix the code per your comments as soon as possible. 
Happy Holidays!

Yuekui

2021-01-28 02:00 UTC, yuekui commented
Hi @pyepye , sorry for the late update. I just simply rebased my branch with yours, and it looks like nothing more need to be done -- your commit fixed all of the code per your comments 👍  
Thanks again for your patient and detailed code review and examples.

2021-01-28 12:15 UTC, pyepye approved these changes
👍

2021-01-28 12:15 UTC, merged

2021-01-28 12:35 UTC, pyepye commented
Hi @yuekui 

Great thanks.

The code has been merged and 0.7.0 has been released to pypi which includes the changes in this pull request 👍 

Happy  coding.